#!/usr/bin/python
#-*-coding:utf-8-*-
#Author:Citron
'''
       Used to save objects generated by parsing XML files
'''
class pdf_xmler:
     def __init__(self,point,char,size):
         self.point=right
         self.size=size
         self.char=char

class pdf_list(list):
    def __init__(self,line_point):
         list.__init__([])
         self.line_point=line_point


class point:
    def __init__(self,top,bottom,left,right):
        self.top=top
        self.bottom=bottom
        self.left=left
        self.right=right
