#!/usr/bin/python
#-*-coding:utf-8-*-
#Author:Citron
'''
       Used to save objects generated by parsing XML files
'''
import copy
#single char text
class pdf_xmler:
     def __init__(self,point,char,size):
         self.point=point
         self.size=int(size)
         self.char=char


#single line text
class pdf_list(list):
    def __init__(self,line_point):
         list.__init__([])
         self.line_point=line_point



#struct point
class point:
    def __init__(self,top,bottom,left,right):
        self.top=int(top)
        self.bottom=int(bottom)
        self.left=int(left)
        self.right=int(right)


class block:
     def __init__(self,line_list):
         self.block_list=[]
         self.line_list=line_list
         self.split_block()

     def split_block(self):
        block=pdf_list(self.line_list[0].point)
        block.append(self.line_list[0])
        for index in range(1,len(self.line_list)):
           if(self.line_list[index].point.left-self.line_list[index-1].point.right<self.line_list[index].size):
                  block.append(self.line_list[index])
  #                print(self.line_list[index].char)
           else:
                  self.block_list.append(copy.deepcopy(block))
                  block.clear()
                  block=pdf_list(self.line_list[index].point)
                  block.append(self.line_list[index])
                  print(1)
        self.block_list.append(copy.deepcopy(block))

