#!/usr/bin/python
#-*-coding:utf-8-*-
#Author:Citron
'''
       Used to save objects generated by parsing XML files
'''
import copy
#single char text
class pdf_xmler:
     def __init__(self,point,char,size):
         self.point=point
         self.size=int(size)
         self.char=char


#single line text
class pdf_list(list):
    def __init__(self,line_point,char_space):
         list.__init__([])
         self.line_point=line_point
         self.char_space=char_space



#struct point
class point:
    def __init__(self,top,bottom,left,right):
        self.top=int(top)
        self.bottom=int(bottom)
        self.left=int(left)
        self.right=int(right)


class block:
     def __init__(self,line_list):
         self.block_list=[]
         self.line_list=line_list
         self.split_block()

     def split_block(self):
        block_char_space=self.get_char_space(0)
        block=pdf_list(self.line_list[0].point,block_char_space )
        block.append(self.line_list[0])
        for index in range(1,len(self.line_list)):
           if(self.line_list[index].point.left-self.line_list[index-1].point.right<self.line_list[index].size):
                  block.append(self.line_list[index])
  #                print(self.line_list[index].char)
           else:
                  self.block_list.append(copy.deepcopy(block))
                  block.clear()
                  block_char_space=self.get_char_space(index)
                  block=pdf_list(self.line_list[index].point,block_char_space)
                  block.append(self.line_list[index])
        self.block_list.append(copy.deepcopy(block))

     def get_char_space(self,index):
         block_char_space=10
         if(len(self.line_list)>index+2):
            block_char_space=self.line_list[index+1].point.left-self.line_list[index].point.right
         return block_char_space 
